### ISSUE TITLE
Jitlinker: wrong adress

### ISSUE THREAD

**Issue by Cr0a3** [Toni-Graphics/rllvm#3]
Memory dump:

**main:**
- **0** mov ecx, 5
- **5** mov edx, 5
- **10** call 26
- **15** ret

**add:**
- **16** add ecx, edx
- **18** mov eax, ecx
- **20** ret

We see at adress 10 - `call 26` - is the adress which is put in wrong. It should be `call 20`
Surly some offset bug

**Comment by Toni-Graphics** [comment]
Small debug said the other function (`add`) isn't in the hashmap: 
```
{"main": ([185, 5, 0, 0, 0, 186, 5, 0, 0, 0, 232, 241, 255, 255, 255, 195], 0)}
```
